Fix min relay fee to be 1s/vB
lightningdevkit/rust-lightning pull request #3457
Opened 2024-12-11 06:31 UTC by arik-so

Bitcoin Core relay policy does not require 16s/vB, which it was
previously set to.

This should address #3438.

2024-12-18 19:37 UTC, tankyleo commented on lightning/src/chain/chaininterface.rs
> +pub const MIN_RELAY_FEE_SAT_PER_1000_WEIGHT: u64 = 253;
Could we delete this in favor of `FEERATE_FLOOR_SATS_PER_KW` below ? Different types, but same number.

2024-12-19 00:32 UTC, tankyleo commented on lightning/src/chain/chaininterface.rs
> +pub const MIN_RELAY_FEE_SAT_PER_1000_WEIGHT: u64 = 253;
Thank you where did you find them ? I've been grepping the bitcoin repo, can't see them.

I agree these are two different settings - I'd suggest we clarify one of them is the incremental fee rate, the other is the broadcast fee rate - "MIN_RELAY_FEE" and "FEERATE_FLOOR" is a little too similar.

2024-12-19 02:23 UTC, tankyleo commented on lightning/src/chain/chaininterface.rs
> +pub const MIN_RELAY_FEE_SAT_PER_1000_WEIGHT: u64 = 253;
could use the names from bitcoin core, `minrelaytxfee` and `incrementalrelayfee`

2024-12-19 17:08 UTC, morehouse reviewed
It would be good to add some unit tests for `feerate_bump`.

2024-12-19 17:08 UTC, morehouse commented on lightning/src/ln/functional_tests.rs
> +		assert!(node_txn.len() <= 6);
If additional bumps can occur, we should verify all of them below (not just the first bump).

2024-12-19 17:08 UTC, morehouse commented on lightning/src/ln/functional_tests.rs
> +		//   plus, depending on the block connection style, two further bumps
So the bumping strategy can vary depending on how the user calls the block connection APIs?

How specifically is bumping affected, and could this lead to transactions not confirming in time?

2025-01-17 18:42 UTC, morehouse reviewed
I still think it would be good to have unit tests specifically for `feerate_bump`.

The CI incremental-mutants failure provides further evidence that such unit tests would be beneficial.

2025-01-17 18:42 UTC, morehouse commented on lightning/src/chain/package.rs
> +	log_trace!(logger, "Fee rate bumped by {}s from {} s/KWU ({} s) to {} s/KWU ({} s) (naive: {} s/KWU ({} s))", new_fee - previous_fee, previous_feerate, previous_fee, new_feerate, new_fee, naive_new_
This naive feerate/fee logging is a little confusing.  IMO we could just remove it.

2025-01-17 19:35 UTC, morehouse reviewed
Did the unit tests pass for you locally?  At least one of them looks incorrect to me.

Also, I'm not sure we should be relying so heavily on pattern matching the logs.  `feerate_bump` is a pure function that we should be able to test by verifying outputs alone.

2025-01-17 19:35 UTC, morehouse commented on lightning/src/chain/package.rs
> +	log_trace!(logger, "Fee rate bumped by {}s from {} s/KWU ({} s) to {} s/KWU ({} s) (naive: {} s/KWU ({} s))", new_fee - previous_fee, previous_feerate, previous_fee, new_feerate, new_fee, naive_new_
I think the log message you added above clarifies things.  We can remove the "(naive: ..)"  logging from this log line now.

2025-01-17 19:35 UTC, morehouse commented on lightning/src/chain/package.rs
> +		log_warn!(logger, "Can't new-estimation bump new claiming tx, output amount {} would end up below dust threshold {}", remaining_output_amount, dust_limit_sats);
Nit: "new-estimation bump" seems confusing.
```suggestion
		log_warn!(logger, "Can't bump new claiming tx, output amount {} would end up below dust threshold {}", remaining_output_amount, dust_limit_sats);
```

2025-01-17 19:35 UTC, morehouse commented on lightning/src/chain/package.rs
> +					log_warn!(logger, "Can't new-estimation bump new claiming tx, output amount {} would end up below dust threshold {}", remaining_output_amount, dust_limit_sats);
Nit: "new-estimation bump" seems confusing.

```suggestion
					log_warn!(logger, "Can't bump new claiming tx, output amount {} would end up below dust threshold {}", remaining_output_amount, dust_limit_sats);
```

2025-01-17 19:35 UTC, morehouse commented on lightning/src/chain/package.rs
> +			logger.assert_log_regex("lightning::chain::package", regex::Regex::new(r"Can't new-estimation bump new claiming tx, output amount 545 would end up below dust threshold 546").unwrap(), 1);
This doesn't seem right...

- Weight: 1000
- Input amount: 861
- Previous feerate: 253
- `new_fee = max(1.25 * 253, 253 + 253) = 506`
- `remaining_output_amount = 861 - 506 = 355`

Yet test test expects output amount of 545.

What am I missing?

2025-01-17 19:35 UTC, morehouse commented on lightning/src/chain/package.rs
> +			let input_satoshis = 2000; // 2000 satoshis
Unhelpful comment.
```suggestion
			let input_satoshis = 2000;
```

2025-01-17 20:24 UTC, morehouse commented on lightning/src/chain/package.rs
> +			logger.assert_log_regex("lightning::chain::package", regex::Regex::new(r"Can't new-estimation bump new claiming tx, output amount 545 would end up below dust threshold 546").unwrap(), 1);
Got it, thanks for explaining.  By the way, it looks like that early termination path can be removed since the dust check is repeated here as well.

2025-01-17 20:27 UTC, morehouse commented
> Can you elaborate on what looks wrong to you? The unit tests are now performing the same checks as they had been originally.

I was referring to the unit test that had a remaining output amount I didn't expect, which you clarified for me.

The unit tests look correct to me, though I would prefer if they didn't rely so heavily on whitebox testing with the log pattern matching.  It would also be good to add a short description to each test case explaining what it's testing.

2025-01-17 21:25 UTC, morehouse commented on lightning/src/chain/package.rs
> +			logger.assert_log_regex("lightning::chain::package", regex::Regex::new(r"Can't new-estimation bump new claiming tx, output amount 545 would end up below dust threshold 546").unwrap(), 1);
My intuition is that during debugging most of the path can be inferred by the amount of the fee bump (e.g., is it 25% or the incremental relay fee), especially for a short, fairly simple function like this one.  In cases where something unexpected could happen, that's when logging is more helpful.

For instance, I'm not sure it's super helpful to have logs like this:

```
... Initiating fee rate bump from X to Y.
... Attempting forced 25% fee rate bump from X to (X*1.25)
... Naive fee bump of (X*.25) does not meet min relay fee of 253
... Fee rate bumped by 253 from X to (X+253)
```

when something like this communicates almost as much:

```
... Fee rate bumped from X to X+253
```

2025-01-21 16:21 UTC, morehouse requested changes

2025-01-21 16:21 UTC, morehouse commented on lightning/src/chain/package.rs
> +	let remaining_output_amount = input_amounts - new_fee;
Yikes!  The `input_amounts <= bumped_fee` short-circuit was removed from the `ForceBump` case above, so now we can get an unsigned underflow here.

2025-01-21 18:32 UTC, morehouse commented on lightning/src/chain/package.rs
> +				let remaining_output_amount = input_amounts - bumped_fee;
Doing the dust check in `feerate_bump` sounds good to me.  But we should also remove the now redundant `max` from `compute_package_output`.

2025-01-23 17:31 UTC, morehouse approved these changes
LGTM

2025-01-23 17:47 UTC, morehouse commented
It couldn't hurt, I suppose.  A fuzz test could assert that the dust limit is never violated and that the incremental fee rate is always satisfied when a fee bump occurs.  It would also detect if the `debug_assert` in `feerate_bump` is ever triggered, though the assert looks trivially correct to me.

If you want to write the test, I'm happy to review it.

2025-01-23 22:31 UTC, merged